# ruff: noqa: E501,I001
"""Generate the DIMER multi-model image-matching workshop notebook."""
from __future__ import annotations
import argparse
import hashlib
import json
from pathlib import Path
from multimodel_image_matching_workshop_source import CELLS

NOTEBOOK_NAME="DIMER_MultiModel_Image_Matching_Workshop.ipynb"
TOOLS=Path(__file__).resolve().parent
LOCK_FILE=TOOLS/"multimodel-image-matching-workshop-requirements.lock"
LOCK_CELL_ID="mat-uv-lock"
ENV_CELL_ID="dimer-matching-workshop-24"
PIECE_LIMIT=1000

def pieces(text,limit=PIECE_LIMIT):
    """Split at line boundaries into pieces of at most ``limit`` characters (a longer line is cut)."""
    out=[]
    current=""
    for line in text.splitlines(keepends=True):
        while len(line)>limit:
            if current:
                out.append(current)
                current=""
            out.append(line[:limit])
            line=line[limit:]
        if current and len(current)+len(line)>limit:
            out.append(current)
            current=""
        current+=line
    if current:
        out.append(current)
    return out

def lock_text():
    data=LOCK_FILE.read_bytes()
    if b"\r" in data:
        raise SystemExit(f"{LOCK_FILE} must use LF line endings")
    return data.decode("utf-8")

def lock_sha256():
    return hashlib.sha256(lock_text().encode("utf-8")).hexdigest()

def lock_cell_source():
    """The carried hash lock: a parenthesised run of string pieces, so no notebook line exceeds 2,000 characters."""
    text=lock_text()
    lines=[
        "# @title Carried hash lock of the matcher environment (infrastructure)",
        "# Generated by tools/build_multimodel_image_matching_workshop.py from",
        "# tools/multimodel-image-matching-workshop-requirements.lock (uv pip compile --generate-hashes,",
        "# CPython 3.12 on x86_64-manylinux_2_28); do not edit by hand.",
        "import hashlib",
        "MATCH_ENV_LOCK = (",
        *(f"    {piece!r}" for piece in pieces(text)),
        ")",
        f"MATCH_ENV_LOCK_SHA256 = {lock_sha256()!r}",
        "if hashlib.sha256(MATCH_ENV_LOCK.encode('utf-8')).hexdigest() != MATCH_ENV_LOCK_SHA256:",
        "    raise RuntimeError('Carried lock integrity failure')",
        "print('Hash lock verified:', sum(1 for line in MATCH_ENV_LOCK.splitlines() if line[:1].isalnum()), 'pinned wheels, SHA-256', MATCH_ENV_LOCK_SHA256)",
    ]
    return "\n".join(lines)

def all_cells():
    cells=[]
    for cell in CELLS:
        if cell.get("id")==ENV_CELL_ID:
            cells.append({"kind":"code","id":LOCK_CELL_ID,"metadata":{"cellView":"form"},"source":lock_cell_source()})
        cells.append(cell)
    if sum(1 for c in cells if c.get("id")==LOCK_CELL_ID)!=1:
        raise SystemExit(f"expected exactly one {ENV_CELL_ID} cell")
    return cells

def build_notebook():
    rendered=[]
    for index,cell in enumerate(all_cells()):
        base={"id":cell.get("id") or f"dimer-matching-workshop-{index:02d}","metadata":cell.get("metadata",{}),"source":cell["source"].splitlines(keepends=True)}
        if cell["kind"]=="markdown":
            rendered.append({"cell_type":"markdown",**base})
        else:
            rendered.append({"cell_type":"code","execution_count":None,"outputs":[],**base})
    return {
        "cells":rendered,
        "metadata":{
            "accelerator":"GPU",
            "colab":{"gpuType":"T4","provenance":[]},
            "dimer":{
                "canonical_runtime":"NVIDIA Tesla T4",
                "capability":"multi-model-image-matching",
                "carrier":"comparative homography-supervised image-matching workshop",
                "clean_runtime_evidence":"pending",
                "credentials_required":False,
                "dataset":"360 CC0 iNaturalist photographs with deterministic three-tier homography pairs",
                "dimer_checkpoint_parity":"qualification-required",
                "notebook_mode":"WORKSHOP",
                "notebook_profile":"TASK-INFERENCE",
                "notebook_spec":"2.1",
                "release_status":"candidate",
                "standalone":True,
                "worker_required":False,
                "review_revisions":[
                    {
                        "date":"2026-10-02",
                        "review":"docs/reviews/2026-10-02-notebook-review/DIMER_MultiModel_Image_Matching_Workshop_Review.md",
                        "reviewed_commit":"024e801760878f967359eef2120f8459fafbd46d",
                        "findings_fixed":["MAT-M1","MAT-M2","MAT-M3","MAT-m1","MAT-m2","MAT-m3","MAT-m4","MAT-m5","MAT-m6"],
                        "evidence":"CPU stand-in checks only; a hosted Run all of this blob is still required",
                    },
                    {
                        "date":"2026-10-03",
                        "change":"Source layout only: PHOTO_MANIFEST_B64 (32,223 characters) and MATCH_RUNNER (8,272 characters) re-serialised as parenthesised runs of string pieces of at most 1000 characters; the joined values are identical, so no cell line exceeds 2000 characters",
                        "evidence":"ast.literal_eval of each new literal equals the old value; a hosted Run all of this blob is still required",
                    },
                    {
                        "date":"2026-10-04",
                        "change":"uv isolated environment brought to the fleet standard: the kernel no longer pip-installs uv; a pinned uv 0.12.15 wheel is downloaded and checked by size and SHA-256, builds a managed CPython 3.12.12 venv and installs a carried hash lock (uv pip compile --generate-hashes, x86_64-manylinux_2_28) with --require-hashes --only-binary :all:; child processes get MPLBACKEND=Agg and no PYTHONPATH/PYTHONHOME/PYTHONSTARTUP; same direct pins (vismatch 1.3.2, torch 2.14.0, torchvision 0.29.0); Linux x86_64 only",
                        "evidence":"local tests and a CPU import audit in a venv built from the lock; a hosted Run all of this blob is still required",
                    },
                ],
                "carried_files":{
                    "requirements.lock.txt":{"source":"tools/multimodel-image-matching-workshop-requirements.lock","sha256":lock_sha256()},
                },
                "generated_from":{
                    "repository":"kurtvalcorza/lightglue-matching-pipeline",
                    "source":"tools/multimodel_image_matching_workshop_source.py",
                    "generator":"tools/build_multimodel_image_matching_workshop.py",
                },
            },
            "kernelspec":{"display_name":"Python 3","name":"python3"},
            "language_info":{"name":"python"},
            "workshop_revision":"0.1.0-candidate",
        },
        "nbformat":4,
        "nbformat_minor":5,
    }

def serialized():
    return json.dumps(build_notebook(),indent=1,ensure_ascii=False)+"\n"

def main():
    parser=argparse.ArgumentParser()
    parser.add_argument("--out",type=Path)
    parser.add_argument("--check",action="store_true")
    args=parser.parse_args()
    repo=Path(__file__).resolve().parents[1]
    out=args.out or repo/"tutorials"/NOTEBOOK_NAME
    content=serialized()
    if args.check:
        if not out.exists() or out.read_text(encoding="utf-8")!=content:
            raise SystemExit(f"STALE: {out}; regenerate the workshop notebook")
        print(f"OK: {out}")
        return 0
    out.write_text(content,encoding="utf-8")
    print(out)
    return 0

if __name__=="__main__":
    raise SystemExit(main())
