"""Per-repository template for tools/build_notebook.py (NOTEBOOK_SPEC 2.2 §4 standalone carrier).

Only the task-specific prose and stage cells live here. The isolated runtime, the embedded package (seven
modules, carried verbatim in dependency order), and the model pin/stage/verify cells are produced by
the generator from repository sources so they cannot drift from the package.

Generator /2.1 keys in use: ``modules`` lists every module of ``src/lightglue_pipeline/`` except
``__init__.py`` (``modeling.py`` is the vendored LightGlue + ALIKED network); ``entry_module`` is
``config.py`` (it holds ``MODEL_ID``/``MODEL_REVISION``/``MODEL_LICENSE`` and the model key under the
package's own spelling ``DEFAULT_MODEL_KEY``, mapped by ``identity_names``); ``model_host`` names the
two GitHub sources (the matcher from a release tag, the extractor from a pinned ALIKED commit) with its own
``pinned`` and ``access`` text (LGC-m2); ``rewrites`` carries two rules — the fleet ``DEFAULT_WEIGHTS_DIR``
rule and the ``__file__`` use inside ``model.resolve_weights_path``; ``model_load`` lets the pipeline pick
CUDA when it is visible. ``isolated_runtime`` (LGC-M1) installs the hash-locked pins into a uv environment
with a managed CPython 3.12.12 and routes every later cell there, so Run all needs no restart;
``infrastructure_labels`` and ``collapse_model_cell`` label and collapse Sections 1-3 (LGC-m6, GDL11).

This template configures an E2E image-matching fine-tuning workflow: the two pinned checkpoint pickles
are digest-verified, statically audited and converted once to safetensors, then loaded strictly into the
vendored network; 360 CC0 iNaturalist photographs are fetched with per-file digests and turned into
homography pairs with exact references (216 / 48 / 96 by photograph, two difficulty tiers — the hard tier
rotates up to ±150°, the regime the frozen matcher fails on); a drawn-shape pair is matched through the
inference contract; the frozen matcher is measured beside three baselines; a bounded fine-tuning of the
matcher's last layers and assignment head runs from the pinned base (Sections 5-7 reload the base first,
LGC-M2/M3); the held-out pairs are scored again per tier and the outcome is recorded, not asserted (LGC-m5);
the adapter is exported and reloaded; Section 10 is an off-by-default change-one-thing experiment on a fresh
copy of the base. Worked answers quote the recorded Kaggle Tesla T4 run of the previous notebook version
(LGC-m3), never the CPU build record as this run's result.
"""
# ruff: noqa: E501  -- markdown prose and code-cell text are kept on single lines for readable rendering

TEMPLATE = {
    "package": "lightglue_pipeline",
    "repo_name": "lightglue-matching-pipeline",
    "stem": "lightglue_matching",
    "notebook_name": "lightglue_matching_colab.ipynb",
    "profile": "E2E",
    "mode": "GUIDED",
    "infrastructure_labels": True,
    "collapse_model_cell": True,
    "isolated_runtime": True,
    # The fleet's uv isolated-environment mechanism (ast-audio-classification-pipeline / bioclip2-biodiversity-pipeline;
    # generator /2.1 as in florence2-vision-language-pipeline 9c4e95a and grounding-dino-detection-pipeline a2bdaaf):
    # managed CPython, a size- and SHA-256-verified uv wheel, and a lock compiled from the pyproject pins with
    # `uv pip compile pyproject.toml -c <detr-detection-pipeline lock @ c3c81cb, versions only> --python-version 3.12
    # --python-platform x86_64-manylinux_2_28 --generate-hashes --only-binary :all: -o tutorials/requirements-colab.lock.txt`.
    # The five pins are a subset of detr-detection-pipeline's (Colab T4 PASS at c3c81cb), so every one of the 33 entries
    # here has that lock's version and hashes.
    "managed_python": "3.12.12",
    "uv": {
        "version": "0.12.15",
        "url": "https://files.pythonhosted.org/packages/1e/fd/432451d732917c49152a291de3ef171aa6b0f1a22d39780fb2c1f085ca4c/uv-0.12.15-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        "bytes": 20081404,
        "sha256": "aee9802f46bae436bd91751bb33ddeb379ef1596b5c19df193219d545d244b60",
    },
    "lock": "tutorials/requirements-colab.lock.txt",
    "pipeline_class": "LightGluePipeline",
    "weights_key": "lightglue-aliked",
    "modules": ["config.py", "modeling.py", "model.py", "metrics.py", "samples.py", "pipeline.py", "provenance.py"],
    "entry_module": "config.py",
    "identity_names": {"MODEL_KEY": "DEFAULT_MODEL_KEY"},
    "model_host": {
        "name": "GitHub (the `cvg/LightGlue` release and the `Shiaoming/ALIKED` repository)",
        "reference_url": "https://github.com/cvg/LightGlue/releases/tag/v0.1_arxiv",
        "revision_label": "release tag",
        # LGC-m2: each source with its own pin; the release tag belongs to cvg/LightGlue only.
        "pinned": (
            "two GitHub files: the matcher `aliked_lightglue.pth` from the immutable `v0.1_arxiv` release of "
            "`cvg/LightGlue` and the extractor `aliked-n16.pth` from `Shiaoming/ALIKED` at the pinned commit `683d7c651973…`"
        ),
        "access": (
            "GitHub only, for the two checkpoint files (about 50 MB together): the matcher `aliked_lightglue.pth` from the "
            "`v0.1_arxiv` release of `cvg/LightGlue` and the extractor `aliked-n16.pth` from `Shiaoming/ALIKED` at commit "
            "`683d7c651973…`, each digest-verified before it is opened. No credentials are required; the two checkpoints are "
            "fetched from GitHub, and nothing is installed from this repository."
        ),
    },
    "rewrites": [
        ["^DEFAULT_WEIGHTS_DIR = Path\\(__file__\\)[^\\n]*$", 'DEFAULT_WEIGHTS_DIR = Path.cwd() / "weights" / DEFAULT_MODEL_KEY  # standalone rewrite (build_notebook.py): working-directory snapshot, no repository checkout'],
        ["^    repo_root = Path\\(__file__\\)\\.resolve\\(\\)\\.parents\\[2\\]$", "    repo_root = Path.cwd()  # standalone rewrite (build_notebook.py): no repository checkout to resolve"],
    ],
    "model_load": "LightGluePipeline.from_pretrained(weights_dir=WEIGHTS_DIR)",
    "runtime_imports": ["torch", "numpy"],
    "title": "LightGlue + ALIKED Matching Pipeline — DIMER E2E matching fine-tuning tutorial (standalone)",
    "badges": [
        (
            "GitHub",
            "https://img.shields.io/badge/GitHub-181717?style=flat&logo=github&logoColor=white",
            "https://github.com/kurtvalcorza/lightglue-matching-pipeline",
        ),
        (
            "Open In Colab",
            "https://colab.research.google.com/assets/colab-badge.svg",
            "https://colab.research.google.com/github/kurtvalcorza/lightglue-matching-pipeline/blob/main/tutorials/lightglue_matching_colab.ipynb",
        ),
        (
            "Upstream",
            "https://img.shields.io/badge/Upstream-cvg%2FLightGlue-181717?style=flat&logo=github&logoColor=white",
            "https://github.com/cvg/LightGlue",
        ),
        (
            "Extractor",
            "https://img.shields.io/badge/Extractor-Shiaoming%2FALIKED-181717?style=flat&logo=github&logoColor=white",
            "https://github.com/Shiaoming/ALIKED",
        ),
        ("arXiv", "https://img.shields.io/badge/arXiv-2306.13643-b31b1b.svg", "https://arxiv.org/abs/2306.13643"),
    ],
    "capability": "sparse local-feature matching (ALIKED keypoints and descriptors matched by the LightGlue transformer, one confidence per correspondence), homography-supervised evaluation and bounded supervised fine-tuning of the matcher's last layers and assignment head on a labelled pair dataset, using the pinned release-tag checkpoints and a vendored network",
    "run_all": (
        "Selecting **Run all** in a fresh supported runtime builds an isolated environment from the hash-locked pins (the "
        "kernel's own packages are left alone, so no restart is needed), fetches the two pinned checkpoint pickles (the "
        "48 MB `aliked_lightglue.pth` from the immutable `v0.1_arxiv` release and the 3 MB `aliked-n16.pth` from a pinned "
        "ALIKED commit), digest-verifies them, audits their pickle streams statically against the fleet's four allowed "
        "globals, converts each once with torch's weights-only unpickler into a safetensors file that is itself "
        "digest-verified, and loads those strictly into the carried network; fetches the 360 pinned iNaturalist "
        "photographs from the project's open-data bucket (about 39 MB, each refused on any byte-size or SHA-256 mismatch), "
        "cuts them per species into 216 / 48 / 96 training, validation and test photographs and turns each into a "
        "homography pair with an exact reference (two difficulty tiers, the hard one rotated up to ±150°); matches a "
        "drawn-shape pair through the inference contract with an input manifest and a rejection probe; measures the frozen "
        "matcher's precision at 3 px, inliers per pair and homography accuracy over the 96 test pairs beside the "
        "identity-guess, patch-nearest-neighbour and descriptor-nearest-neighbour baselines and draws its matches on an easy "
        "and a rotated pair; runs a bounded fine-tuning of the matcher's last two layers and assignment head from the pinned "
        "base with the LightGlue assignment loss on cached ALIKED features and validation-precision epoch selection; scores "
        "the held-out pairs again per tier and records the outcome; re-matches the drawn pair with the adapted model; "
        "exports the adapter as safetensors with a manifest; and reloads that artifact into a fresh pipeline to verify "
        "match parity. The optional Section 10 experiment is off by default. The default path needs no repository clone, "
        "no DIMER worker or service, no credential, no upload dialog and no configuration edit (NOTEBOOK_SPEC 2.2 §5). A "
        "CUDA runtime is used automatically when present: in the recorded Kaggle Tesla T4 run of the previous notebook "
        "version the whole path took about 21 minutes including the downloads, of which the three baselines took 441 s "
        "(the patch nearest neighbour is a brute-force NumPy search that runs on the CPU even on a GPU runtime). On CPU "
        "alone the path took about 61 minutes on the build workstation after the downloads; expect longer on a 2-vCPU "
        "hosted runtime. The long stages print their progress. Building the isolated environment comes on top of this."
    ),
    "byod": (
        "After the tutorial workflow completes, set `USE_BYOD = True` in Section 4, select that cell and choose **Runtime → "
        "Run after** (it re-runs Section 4 and every later cell; Sections 5, 6 and 7 reload the pinned base matcher first, "
        "so the earlier adaptation never carries over into a *frozen* number or into the next training run). Supply one zip "
        "of JPEG / PNG photographs through the upload dialog on Colab, or a zip or folder path in `BYOD_PATH` on any runtime. "
        "It needs **at least 12 distinct photographs** (any subject, ideally textured): the seeded split keeps 20 % for test "
        "and 15 % for validation but never fewer than 4 photographs in any split, so 12 is the smallest set that leaves "
        "4 / 4 / 4; Section 4 checks this before any matching runs, names the split it refuses, reports pixel-duplicate "
        "photographs it drops, and reports every photograph it has to **upscale** to the 640 px working size. Each "
        "photograph becomes one homography pair with the same seeded warps and passes through the same validation, "
        "baselines, fine-tuning, held-out evaluation, artifact export and reload-parity cells as the iNaturalist sample; "
        "an adapted matcher that scores below the frozen one is reported, not treated as an error. Uploaded files stay "
        "inside this runtime. BYOD is optional and never part of the default path. Real pairs of two different photographs "
        "of one scene need a reference homography or depth to be scored; the contract accepts only synthesised pairs with "
        "an exact `H`."
    ),
    "intro": (
        "LightGlue (Lindenberger, Sarlin and Pollefeys, ICCV 2023) is a sparse matcher: given two sets of keypoints with "
        "descriptors it runs nine transformer layers of self- and cross-attention with rotary positional encoding, then a "
        "unified assignment head (matchability per keypoint and a dual-softmax over descriptor similarities) that returns, for "
        "each mutual best match above a threshold, one confidence. The keypoints and descriptors come from ALIKED-N(16) (Zhao "
        "et al., 2023), a deformable-convolution detector-descriptor. The checkpoints are two GitHub files, not a Hugging Face "
        "repository: `aliked_lightglue.pth` is an asset of the immutable `v0.1_arxiv` release of `cvg/LightGlue` (**Apache-2.0**; "
        "11,884,625 parameters, 253 tensors) and `aliked-n16.pth` a file of `Shiaoming/ALIKED` at a pinned commit "
        "(**BSD-3-Clause**; 677,356 parameters). Both are plain PyTorch pickles: this notebook audits them statically, converts "
        "each once with the weights-only unpickler to a safetensors file and loads only those. The matcher's adaptive early "
        "exit and point pruning are switched off, so every pair runs all nine layers on every keypoint. The confidences are "
        "assignment scores, **not calibrated probabilities** that a match is right, and the matcher never abstains — any two "
        "images produce whatever passes the threshold, overlapping or not. This repository carries both networks as plain "
        "PyTorch (`modeling.py`, vendored from the upstream commits) so no third-party matching framework is installed.\n\n"
        "What this notebook adds to inference is **adaptation with labelled pairs** — pairs whose correct answer is known "
        "exactly. The images are real: 360 CC0-licensed, research-grade iNaturalist photographs of six bird species (**CC0 "
        "1.0**; the fleet's SigLIP sample, 60 per species, one per observer), pinned by photo id, byte size and SHA-256 and "
        "fetched from the project's open-data bucket at run time. Each photograph becomes one pair with a seeded homography "
        "warp and seeded photometric changes, so every returned match has a **reprojection error** against the reference `H`. "
        "Two tiers alternate: `easy` (small perspective, ±10°, mild photometry) and `hard` (large perspective, **rotation up to "
        "±150°**, scale 0.6–1.4, strong photometry). The rotation is the point: ALIKED descriptors and LightGlue's positional "
        "encoding are not rotation-invariant — in the recorded Kaggle Tesla T4 run the frozen matcher reached 0.750 "
        "precision at 3 px over the 96 test pairs, 0.999 on the easy tier and **0.500 on the rotated tier** — so the honest "
        "question is whether a bounded fine-tuning of the matcher's last layers on 216 pairs (half of them rotated) moves "
        "**precision at 3 px**, the **inlier count** and the **homography accuracy** on an image-disjoint test split, per "
        "tier, against three **baselines** (the **identity guess**, a **patch nearest neighbour**, and the same ALIKED "
        "keypoints matched by **descriptor nearest neighbour** without the learned matcher). Nothing here is a quality claim "
        "about your images: it is one seeded split of one sample under synthetic warps.\n\n"
        "**Snapshot note:** the manifest in Section 3 lists the two source pickles with their sizes, digests, source URLs and "
        "static-audit digests, and the safetensors file each converts to with its own size and digest. Section 3 stages the "
        "sources, verifies them, converts them once and verifies the conversions before the networks are constructed; a "
        "re-run that finds the safetensors files present never opens a pickle again.\n\n"
        "**Who this is for.** A learner who knows basic Python, NumPy and PIL, has met the idea of a pretrained model, and "
        "wants to see how a learned feature matcher is measured against exact references and adapted with labelled pairs. "
        "No prior experience with LightGlue, homographies, matching metrics or fine-tuning is assumed: each term is explained "
        "where it is first used and again in the **Glossary** at the end. A CPU runtime works (slowly); a GPU runtime "
        "finishes in about 20 minutes (Prerequisites).\n\n"
        "**Input → Model → Output.**\n\n"
        "| | Inference | Fine-tuning |\n"
        "|---|---|---|\n"
        "| Input | two images (sides 64 to 1,024 px after preparation) | 216 training pairs, each a photograph, its warped copy and the exact 3 × 3 homography `H` between them |\n"
        "| Model | ALIKED-N(16) keypoints + 128-d descriptors per image → LightGlue: nine self/cross-attention layers → assignment head | the same networks with the matcher's last two layers and assignment head trained (2.57 M of 11.88 M parameters), ALIKED and the earlier layers frozen |\n"
        "| Output | matched keypoints `kpts0` ↔ `kpts1` in pixel coordinates, one assignment confidence per match — not a probability | an adapter (safetensors) and held-out precision, inliers and homography accuracy per tier beside three baselines and the frozen matcher |\n\n"
        "**How to use this notebook.** Choose a runtime (a GPU is faster, CPU works), then **Runtime → Run all**. Sections "
        "1–3 are **infrastructure** — the isolated environment, the carried code and the checkpoint verification — and can "
        "be run without study; their code is collapsed. The learning path starts in Section 4. Form fields (`# @param`) are "
        "the only values meant to be edited; the defaults reproduce the recorded path. Each stage asks you to **predict** "
        "before it runs, and the next cell opens with **What to notice** and a collapsible **Check your reasoning** block "
        "with a worked answer from the recorded Kaggle Tesla T4 run of the previous notebook version (same model stages and "
        "data; your numbers can differ in the third decimal, and the fine-tuning result by about a hundredth — see "
        "**Run-to-run spread** in Section 7). Section 10 is a **change-one-thing experiment**, off by default. "
        "**Troubleshooting**, a **Glossary** and a **Conclusion** template are at the end. Your notes are optional and are "
        "not required submissions.\n\n"
        "**Roadmap:** 4 fetch the photographs and build the pairs → 5 match a drawn pair through the inference contract → "
        "6 three baselines and the frozen matcher on the test pairs → 7 fine-tune the matcher's last layers → 8 compare on "
        "the held-out pairs → 9 re-match the drawing, export and reload → 10 **change one thing: train four layers instead "
        "of two** → conclude. Core concepts are Sections 5 and 6 (what the matcher returns and how it is scored); evaluation "
        "practice is Sections 4, 7 and 8 (split, selection, held-out comparison); engineering and reproducibility are "
        "Sections 1–3 and 9."
    ),
    "learning_objectives": (
        "by the end you should be able to (1) explain *two images → ALIKED keypoints and descriptors → LightGlue's nine "
        "layers → mutual matches with confidences* and say why a confidence is not a probability and why the matcher never "
        "abstains (Section 5); (2) read precision at 3 px, inliers per pair and homography accuracy against the identity, "
        "patch and descriptor baselines, per tier, and say what each baseline rules out (Section 6); (3) explain how the "
        "validation split, never the test split, chooses the kept epoch, and why epoch 0 is the frozen matcher (Section 7); "
        "(4) predict and then check how each tier moves after a bounded fine-tuning, and say why the easy tier cannot move "
        "much (Section 8); (5) say what a photograph-disjoint split does and does not protect against (Sections 4 and 8); "
        "(6) check that an exported adapter reproduces the evaluated matcher (reload parity, Section 9); and (7) predict and "
        "then observe what training four layers instead of two changes (Section 10)."
    ),
    "exclusions": (
        "object detection, semantic segmentation, OCR, caption generation, calibrated match probabilities or universal "
        "thresholds, geometric verification inside the pipeline (the evaluation's RANSAC is a metric, not a filter), pose or "
        "depth estimation, dense or detector-free matching, other extractors (SuperPoint, DISK, SIFT — LightGlue has "
        "checkpoints for each; only the ALIKED one is carried), the adaptive early exit and point pruning of the upstream "
        "demo, fine-tuning of the extractor, the input projection, the positional encoding or the earlier matcher layers, "
        "training on images that are not the pinned sample or your own uploads, evaluation on HPatches, MegaDepth or any "
        "benchmark proper (only one seeded 360-pair sample is scored here), and any claim that six bird species stand in for "
        "your scenes. The repository exposes none of these."
    ),
    "prerequisites": [
        "- **Learner:** basic Python, NumPy and PIL, and Colab or Jupyter familiarity. No prior experience with LightGlue, homographies, matching metrics or fine-tuning: the notebook explains keypoints and descriptors, the homography `H` and reprojection error, precision at 3 px, inliers, RANSAC homography accuracy, the three baselines and validation-based epoch selection where they are first used, and the Glossary repeats them.",
        "- **Runtime:** a fresh **Linux x86_64** runtime — Google Colab, Kaggle or Linux Jupyter. Section 1 builds its own **Python 3.12.12** environment from a hash-locked list of manylinux wheels, so the kernel's own Python version does not matter (Colab's kernel runs Python 3.13 as of September 2026; the stages still run on 3.12.12), and a Windows or macOS kernel is not supported (Section 1 stops with that message). The default path runs on CPU (float32) and uses CUDA automatically when available. In the recorded Kaggle Tesla T4 run of the previous notebook version (Python 3.12.13 in the kernel) the whole path took about 21 minutes including the downloads: the three baselines 441 s (the patch nearest neighbour is a brute-force NumPy search on the CPU), the fine-tuning 130 s. On the build workstation's CPU the baselines took about 19 minutes and the fine-tuning about 35; a 2-vCPU hosted CPU runtime is slower still, and every long stage prints its progress. The locked install (PyTorch 2.14.0 with its CUDA libraries, a few GB) is the largest download; the checkpoints are about 50 MB and the photographs about 39 MB.",
        "- **Knowledge:** what a homography is and why a warped copy of an image has an exact correspondence for every pixel; what precision, reprojection error and RANSAC measure and why none is a human judgement; why 96 pairs from one seeded draw give no dispersion estimate; why a self-drawn scene is a plumbing check while an image-disjoint split of one sample is a measurement of that sample only; why a matcher that never abstains needs its baselines read first. Each is explained again where it is used.",
        "- **Data contract:** records are `{id, image0, image1, homography}` — two PIL images (or files decodable by Pillow) with sides in [64, 1024] px (the sample is built at 640 px on the long side, sides multiples of 8) and a finite, non-singular 3 × 3 `H` mapping image0 coordinates to image1 coordinates; the sample records also carry `tier` and `seed`. Between 4 and 5,000 records per split. BYOD is one zip or folder of JPEG / PNG photographs which the contract turns into pairs itself; each split must hold at least 4 pairs, so **a BYOD dataset needs at least 12 distinct photographs** (Section 4 computes and prints this minimum, checks it before any matching runs and names the split it refuses). Every photograph is brought to 640 px on its long side, so a smaller one is **upscaled**; Section 4 reports each one, and one under 64 px on a side is flagged.",
        "- **BYOD layout:** one zip (by upload on Colab, or by path in `BYOD_PATH` on any runtime; a folder path also works) holding JPEG / PNG photographs; their folders inside the zip are ignored. An optional `images.csv` is not needed.",
        "- **Validation is structural, not semantic:** every image is opened and decoded and every `H` checked for shape and rank, but nothing checks that `image1` really is `image0` under `H` — a wrong reference is scored without complaint and the numbers are then meaningless. The tutorial's references are exact by construction.",
        "- **Privacy:** Do not upload confidential or restricted data to a hosted runtime unless you are authorized to process it there. The default path uploads nothing.",
        "- **External access (data):** besides the two checkpoint files, the default path fetches 360 JPEG/PNG files from `https://inaturalist-open-data.s3.amazonaws.com/photos/<id>/medium.<ext>` (about 39 MB in total), each pinned by byte size and SHA-256 in the carried `samples.py`; a cached copy under `weights/inat-birds/` is re-hashed and used when present.",
    ],
    "cells": [
        {
            "md": (
                "## 4. iNaturalist photographs, homography pairs and split\n\n"
                "`fetch_corpus` returns the 360 pinned photographs from the cache under `weights/inat-birds/` or the "
                "iNaturalist open-data bucket — every cached file is re-hashed and every fetched file refused on any byte-size or "
                "SHA-256 mismatch — and `read_corpus` decodes them into image records with their observation page, observer and "
                "species. `build_sample_dataset` draws a seeded stratified split of photographs per species (36 / 8 / 16 → 216 / "
                "48 / 96) and turns each photograph into one pair: the photograph at 640 px on the long side (`image0`) and a "
                "copy warped by a seeded homography with seeded photometric changes (`image1`), tiers alternating `easy` / "
                "`hard`, the reference `H` recorded in the record. `validate_dataset` then checks every split against the "
                "contract and its own minimum, `check_split_disjoint` checks that no photograph (by decoded-pixel digest) is "
                "shared, `observer_overlap` reports how many observers contributed to more than one split (an observation about "
                "the draw, not an assertion), and the training split's pair table is written to `outputs/{stem}_train.csv`.\n\n"
                "**Bring your own data:** set `USE_BYOD = True`, either leave `BYOD_PATH` empty to get an upload dialog "
                "(Colab only) or set it to a zip or folder already in this runtime, then select this cell and choose **Runtime → "
                "Run after**. An empty or cancelled upload, a runtime without the Colab upload dialog and no `BYOD_PATH`, or a "
                "path that does not exist each stop with a message naming the next step.\n\n"
                "Look for: 360 photographs, three splits with both tiers, three digests, one pair with its reference corners, the "
                "tier parameters (the hard tier's `rotation` of 150°), the BYOD minimum, and four refusal probes — a duplicate id, "
                "an image over the side ceiling, a singular homography and a dataset too small to split — each rejected before the "
                "model does anything.\n\n"
                "**Predict before running:** how many pairs will each split hold, how many photographs will appear in two "
                "splits, and will some *observers* appear in two splits anyway?"
            ),
            "code": (
                "import hashlib\n"
                "import json\n"
                "import time\n\n"
                "import numpy as np\n"
                "from PIL import Image, ImageDraw\n\n"
                "USE_BYOD = False  # @param {{type:\"boolean\"}}\n"
                "BYOD_PATH = ''  # @param {{type:\"string\"}}\n"
                "SPLIT_SEED = 42  # @param {{type:\"integer\"}}\n\n"
                "os.makedirs('outputs', exist_ok=True)\n"
                "byod = None\n"
                "if USE_BYOD:\n"
                "    if BYOD_PATH.strip():\n"
                "        byod_source = Path(BYOD_PATH.strip()).expanduser()\n"
                "        if not byod_source.exists():\n"
                "            raise FileNotFoundError(f'BYOD_PATH = {{BYOD_PATH!r}} does not exist in this runtime: fix the path, or leave BYOD_PATH empty to upload a zip in Colab.')\n"
                "        file_name, payload = byod_source.name, (byod_source.read_bytes() if byod_source.is_file() else None)\n"
                "    else:\n"
                "        try:\n"
                "            from google.colab import files\n"
                "        except ImportError:\n"
                "            raise RuntimeError('The upload dialog needs Google Colab. Elsewhere, put the zip (or folder) in this runtime and set BYOD_PATH to its path.') from None\n"
                "        uploaded = files.upload()\n"
                "        if len(uploaded) != 1:\n"
                "            raise ValueError(f'Upload exactly one .zip file (received {{len(uploaded)}}). Run this cell again and choose a file, or set BYOD_PATH to a zip or folder already in this runtime.')\n"
                "        file_name, payload = next(iter(uploaded.items()))\n"
                "        byod_source = Path('work') / 'byod.zip'\n"
                "        byod_source.parent.mkdir(parents=True, exist_ok=True)\n"
                "        byod_source.write_bytes(payload)\n"
                "    records = load_byod_dataset(byod_source)\n"
                "    unique_records, dropped_duplicates = distinct_images(records)\n"
                "    byod_low, byod_high = byod_record_limits()\n"
                "    print({{'byod_photographs': len(records), 'distinct': len(unique_records), 'pixel_duplicates_dropped': len(dropped_duplicates), 'dropped_ids': dropped_duplicates[:20], 'needed': f'{{byod_low}}..{{byod_high}} distinct photographs'}})\n"
                "    upscaling = upscaling_report(unique_records)\n"
                "    if upscaling['upscaled']:\n"
                "        print({{'upscaled_to_working_size': upscaling['upscaled'], 'working_long_side_px': upscaling['working_long_side'], 'largest_factor': upscaling['largest_factor'], 'under_64_px_on_a_side': upscaling['under_min_side'][:20], 'first': upscaling['details'][:3]}})\n"
                "        print('Note: these photographs were enlarged to 640 px before warping; pairs built from a heavily upscaled photograph measure the interpolation as much as the matcher.')\n"
                "    splits = split_dataset(unique_records, seed=SPLIT_SEED)\n"
                "    data_source = 'BYOD (' + file_name + ')'\n"
                "    raw_rows = {{'byod_photographs': len(records), 'distinct': len(unique_records)}}\n"
                "    byod = {{'file': file_name, 'photographs': len(records), 'distinct': len(unique_records), 'duplicates_dropped': dropped_duplicates, 'upscaling': upscaling, 'zip_sha256': hashlib.sha256(payload).hexdigest() if payload is not None else None}}\n"
                "else:\n"
                "    corpus_files = fetch_corpus(cache_dir='weights/inat-birds')\n"
                "    corpus = read_corpus(corpus_files)\n"
                "    splits = build_sample_dataset(corpus, seed=SPLIT_SEED)\n"
                "    data_source = f'{{CORPUS_NAME}}: {{CORPUS_RELEASE}} ({{CORPUS_LICENSE}}); one seeded homography pair per photograph'\n"
                "    raw_rows = {{'photographs': len(corpus), 'bytes': sum(len(v) for v in corpus_files.values()), 'observers': len({{r['observer'] for r in corpus}})}}\n"
                "minimums = split_minimums()\n"
                "dataset_manifests = {{name: validate_dataset(part, min_records=minimums[name]) for name, part in splits.items()}}\n"
                "splits = {{name: manifest['records'] for name, manifest in dataset_manifests.items()}}\n"
                "disjoint = check_split_disjoint(splits)\n"
                "train_records, val_records, test_records = splits['train'], splits['validation'], splits['test']\n"
                "write_dataset_csv(train_records, 'outputs/{stem}_train.csv')\n"
                "print({{'data_source': data_source, 'raw_rows': raw_rows, 'splits': disjoint, 'split_unit': 'photograph (decoded pixels)', 'observer_overlap': observer_overlap(splits), 'tiers': {{k: v for k, v in TIER_PARAMS.items()}}}})\n"
                "print({{'byod_minimum_distinct_photographs': byod_record_limits()[0], 'split_minimums': minimums}})\n"
                "for name, manifest in dataset_manifests.items():\n"
                "    print({{name: {{'n': manifest['n_records'], 'tiers': manifest['tiers'], 'image_side': manifest['image_side'], 'digest': manifest['digest'][:16] + '...'}}}})\n"
                "example = train_records[0]\n"
                "corners = np.array([[0.0, 0.0], [example['image0'].width - 1.0, 0.0], [example['image0'].width - 1.0, example['image0'].height - 1.0], [0.0, example['image0'].height - 1.0]])\n"
                "print({{'example': {{'id': example['id'], 'tier': example['tier'], 'size': list(example['image0'].size), 'corners_under_H': np.round(warp_points(corners, np.asarray(example['homography'])), 1).tolist(), 'observation': example.get('inat_observation_url')}}}})\n"
                "probes = {{\n"
                "    'duplicate id': [{{**r, 'id': 'same'}} for r in train_records[:8]],\n"
                "    'image over the side ceiling': [{{**train_records[0], 'image0': Image.new('RGB', (MAX_IMAGE_SIDE + 1, 8))}}, *train_records[1:8]],\n"
                "    'singular homography': [{{**train_records[0], 'homography': [[1, 0, 0], [1, 0, 0], [0, 0, 1]]}}, *train_records[1:8]],\n"
                "    'too small': train_records[:3],\n"
                "}}\n"
                "for name, probe in probes.items():\n"
                "    try:\n"
                "        validate_dataset(probe)\n"
                "        print({{'probe': name, 'verdict': 'accepted'}})\n"
                "    except (TypeError, ValueError) as exc:\n"
                "        print({{'probe': name, 'rejected': str(exc)[:110]}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the three split sizes, both tiers in every split, `split_unit`, the observer overlap, the "
                "BYOD minimum (12) and the four rejections.\n\n"
                "<details><summary>Check your reasoning</summary>216, 48 and 96 pairs, half of each `easy` and half `hard`, and "
                "no photograph in two splits — `check_split_disjoint` compares decoded pixels, so a re-encoded copy would be "
                "caught too. But the split is by *photograph*, not by *observer*: in the recorded T4 run 53 of the 222 observers "
                "had photographs in more than one split. That is printed, not refused, because every pair is a synthetic warp of "
                "one photograph — the matcher never sees the same scene twice across splits. On real data split by scene, "
                "session or photographer. The BYOD minimum of 12 is the smallest set whose seeded split leaves 4 training, 4 "
                "validation and 4 test pairs.</details>\n\n"
                "## 5. Match through the inference contract\n\n"
                "The inference contract is exercised on a drawn pair: a 256 × 192 synthetic scene — a red square, a green circle "
                "and a blue triangle on a light background with a faint grid, rendered in code exactly as the repository's "
                "`examples/sample-data/generate_samples.py` renders it and digest-asserted against `SHA256SUMS` — and its copy "
                "under a fixed reference homography, a different image family from the photographs and a pair the matcher will "
                "be asked to match again after adaptation. `validate_inputs` applies exactly the checks `match` applies and "
                "returns an input manifest; a remote URL is validated too and its rejection recorded as a finding. `match` returns "
                "`kpts0`, `kpts1` and one confidence per correspondence — ALIKED keypoints of image0 and their mutual best "
                "partners in image1 above the match threshold, in keypoint-score order; the per-pair `evaluation_report` on a "
                "drawing is `sample-sanity` — plumbing evidence, not a measurement; whether the matcher is *right* is what "
                "Section 6 measures on 96 photograph pairs.\n\n"
                "**Every pass starts from the pinned base.** Section 7 changes the matcher in memory. If this cell, Section 6 or "
                "Section 7 runs again after Section 7 (a BYOD run, or a changed Section 7 field with **Run after**), it first "
                "reloads the pinned base matcher from the verified snapshot with `reset_to_pretrained()`, so a *frozen* number is "
                "never read from an adapted matcher and a new training run never starts from the previous one. This cell also "
                "defines `show_progress`, which the long stages use to print a progress line at least every 30 seconds.\n\n"
                "**Predict before running:** a drawing of flat shapes has few corners. Roughly how many matches will the frozen "
                "matcher return — tens, hundreds or thousands — and what share of them will land within 3 px of where `H` says "
                "they should?"
            ),
            "code": (
                "import gc\n\n"
                "PROGRESS_EVERY_S = 30\n"
                "_progress_last = {{}}\n\n\n"
                "def show_progress(event):\n"
                "    \"\"\"Print a long stage's progress at most every PROGRESS_EVERY_S seconds and when it finishes.\"\"\"\n"
                "    if event['done'] == 1:\n"
                "        _progress_last[event['stage']] = 0.0\n"
                "    if event['done'] == event['of'] or event['seconds'] - _progress_last.get(event['stage'], 0.0) >= PROGRESS_EVERY_S:\n"
                "        _progress_last[event['stage']] = event['seconds']\n"
                "        print({{'progress': event['stage'], 'pairs': f\"{{event['done']}}/{{event['of']}}\", 'seconds': event['seconds']}})\n\n\n"
                "def reset_to_pretrained():\n"
                "    \"\"\"Sections 5-7 start from the pinned base: if an earlier pass adapted `pipe`, reload it from the verified snapshot.\"\"\"\n"
                "    global pipe\n"
                "    if pipe.adapter is None:\n"
                "        return\n"
                "    pipe = None\n"
                "    gc.collect()\n"
                "    pipe = LightGluePipeline.from_pretrained(weights_dir=WEIGHTS_DIR)\n"
                "    print({{'reloaded': 'the pinned base matcher, from the verified snapshot', 'reason': 'an earlier pass had adapted the matcher in memory'}})\n\n\n"
                "reset_to_pretrained()\n"
                "SAMPLE_DIGESTS = {{  # examples/sample-data/SHA256SUMS\n"
                "    'shapes_scene.ppm': '3420b1d3755a5bf9bc90803fa50f3fc7bbeca5720bd6d75748ad79ac00908239',\n"
                "}}\n"
                "SHAPES_H = np.array([[0.96, 0.05, 12.0], [-0.04, 1.03, -7.0], [2e-5, -1e-5, 1.0]])\n"
                "WIDTH, HEIGHT, BACKGROUND = 256, 192, (245, 245, 245)\n\n\n"
                "def scene_pixel(x, y):\n"
                "    if 40 <= x < 104 and 48 <= y < 112:\n"
                "        return (220, 40, 40)\n"
                "    if (x - 168) ** 2 + (y - 80) ** 2 <= 34 ** 2:\n"
                "        return (40, 170, 75)\n"
                "    if 128 <= y < 176 and abs(x - 120) <= (y - 128) // 2:\n"
                "        return (40, 90, 220)\n"
                "    if x % 32 == 0 or y % 32 == 0:\n"
                "        return (200, 200, 200)\n"
                "    return BACKGROUND\n\n\n"
                "def render_scene():\n"
                "    # The repository's generate_samples.py rendering: ASCII P3, 24 values per line.\n"
                "    lines = ['P3', f'{{WIDTH}} {{HEIGHT}}', '255']\n"
                "    for y in range(HEIGHT):\n"
                "        row = []\n"
                "        for x in range(WIDTH):\n"
                "            row.extend(str(v) for v in scene_pixel(x, y))\n"
                "        for start in range(0, len(row), 24):\n"
                "            lines.append(' '.join(row[start : start + 24]))\n"
                "    return '\\n'.join(lines) + '\\n'\n\n\n"
                "Path('outputs/sample-data').mkdir(parents=True, exist_ok=True)\n"
                "scene_path = Path('outputs/sample-data/shapes_scene.ppm')\n"
                "scene_path.write_bytes(render_scene().encode('ascii'))\n"
                "scene_digest = hashlib.sha256(scene_path.read_bytes()).hexdigest()\n"
                "if scene_digest != SAMPLE_DIGESTS['shapes_scene.ppm']:\n"
                "    raise ValueError(f'Synthetic sample digest mismatch: {{scene_digest}} != {{SAMPLE_DIGESTS[\"shapes_scene.ppm\"]}}')\n"
                "scene0 = Image.open(scene_path).convert('RGB')\n"
                "scene1 = warp_image(scene0, SHAPES_H)\n"
                "scene1_path = Path('outputs/sample-data/shapes_scene_warped.png')\n"
                "scene1.save(scene1_path)\n"
                "print({{'ceilings': {{'MIN_SIDE': MIN_SIDE, 'MAX_SIDE': MAX_SIDE, 'DIVISIBLE_BY': DIVISIBLE_BY, 'MAX_IMAGE_SIDE': MAX_IMAGE_SIDE, 'MIN_RECORDS': MIN_RECORDS, 'MAX_RECORDS': MAX_RECORDS, 'keypoints': INPUT_SCHEMA['keypoints'], 'thresholds': INPUT_SCHEMA['thresholds'], 'device': str(pipe.device)}}}})\n"
                "input_manifest = validate_inputs(scene_path, scene1_path, names=[scene_path.name, scene1_path.name])\n"
                "try:\n"
                "    validate_inputs('https://example.invalid/not-allowed.png', scene1_path)\n"
                "except ValueError as exc:\n"
                "    input_manifest['findings'].append({{'input': 'remote-url-probe', 'verdict': 'rejected', 'message': str(exc)}})\n"
                "with open('outputs/{stem}_input_manifest.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(input_manifest, handle, indent=2, ensure_ascii=False)\n"
                "print({{'scene_sha256': scene_digest[:16] + '...', 'manifest_verdict': input_manifest['verdict'], 'findings': len(input_manifest['findings'])}})\n"
                "t0 = time.perf_counter()\n"
                "scene_match = pipe.match(scene_path, scene1_path)\n"
                "scene_errors = reprojection_errors(scene_match['kpts0'], scene_match['kpts1'], SHAPES_H)\n"
                "checks = {{\n"
                "    'same_length': len(scene_match['kpts0']) == len(scene_match['kpts1']) == len(scene_match['confidence']),\n"
                "    'coordinates_inside_frames': bool(np.all(scene_match['kpts0'] >= 0) and np.all(scene_match['kpts0'][:, 0] < scene_match['size0'][0]) and np.all(scene_match['kpts0'][:, 1] < scene_match['size0'][1])),\n"
                "    'confidences_in_unit_interval': bool(np.all((scene_match['confidence'] > 0) & (scene_match['confidence'] <= 1))),\n"
                "    'some_matches': len(scene_match['kpts0']) > 0,\n"
                "}}\n"
                "if not all(checks.values()):\n"
                "    raise RuntimeError(f'inference output failed a sanity check: {{checks}}')\n"
                "frozen_scene = evaluation_report(scene_match, {{'homography': SHAPES_H, 'size': scene_match['size0']}}, sample_kind='synthetic')\n"
                "scene_rows = {{'frozen': {{'n_matches': int(len(scene_match['kpts0'])), 'precision_3px': float((scene_errors < 3).mean()) if len(scene_errors) else 0.0, 'median_error_px': float(np.median(scene_errors)) if len(scene_errors) else None}}}}\n"
                "print({{'checks': checks, 'seconds': round(time.perf_counter() - t0, 2), 'frozen_scene': {{m['id']: round(m['value'], 3) for m in frozen_scene['metrics']}}, 'verdict': frozen_scene['verdict'], 'first_matches': np.round(np.concatenate([scene_match['kpts0'][:3], scene_match['kpts1'][:3]], axis=1), 1).tolist()}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the ceilings line (sides, record counts, the keypoint budget and the match threshold are "
                "caller-owned contract values, not calibrations), the four `checks`, the rejected remote URL in the manifest, "
                "and the scene's match count and precision.\n\n"
                "<details><summary>Check your reasoning</summary>Tens. In the recorded T4 run the frozen matcher returned 32 "
                "matches on the drawing and all 32 were within 3 px (precision 1.000, corner error 0.47 px): ALIKED finds "
                "keypoints on corners and edges, and a drawing of three filled shapes and a grid has few of them. A perfect score "
                "on one self-drawn pair is plumbing evidence — the contract runs and the coordinates are in the right frames — "
                "not a measurement of the matcher.</details>\n\n"
                "## 6. Baselines and the frozen matcher on the test pairs\n\n"
                "Four systems frame the adaptation, each read the same way. The **identity guess** answers that every grid "
                "point of image0 is at the same coordinates in image1 — right only where the warp is tiny. The **patch nearest "
                "neighbour** answers with the best normalised-cross-correlation 15 × 15 patch within ±48 px — a matcher that "
                "knows the images through raw intensities and nothing else. The **descriptor nearest neighbour** takes the same "
                "ALIKED keypoints and descriptors the model sees and matches them by mutual nearest neighbour in descriptor "
                "space — what the pipeline is without its learned matcher, so the gap to it is what LightGlue's nine layers "
                "buy. The **frozen model** is scored by `pipe.evaluate`: every returned match against the reference `H`, "
                "**precision at 3 px** (also 1 px and 5 px), **matches and inliers per pair** (an inlier is a match within 3 px), "
                "the **median error** of the inliers, and **homography accuracy at 3 px / 5 px** — the fraction of pairs whose "
                "RANSAC-DLT homography from the matches moves the image corners by less than the threshold against the "
                "reference, the HPatches-style reading. All four are scored per tier as well. The cell then draws the frozen "
                "matcher's matches on one easy and one rotated test pair (green within 3 px, red beyond) and saves the figure as "
                "`outputs/{stem}_correspondences.png`.\n\n"
                "**Expected wait:** the patch nearest neighbour is a brute-force NumPy search that runs on the CPU on every "
                "runtime — 409 s of the 441 s the three baselines took in the recorded T4 run, and about 17 minutes of 19 on the "
                "build workstation's CPU. A progress line is printed at least every 30 seconds.\n\n"
                "**Predict before running:** on which tier will the frozen matcher fail, and why? Will it beat the descriptor "
                "nearest neighbour — the same keypoints without the nine layers — by much on the easy tier?"
            ),
            "code": (
                "METRICS = ('precision_3px', 'precision_1px', 'matches_per_pair', 'inliers_per_pair', 'median_error_px', 'homography_acc_3px', 'homography_acc_5px')\n\n\n"
                "def short(result):\n"
                "    return {{k: (round(result[k], 3) if isinstance(result[k], float) and np.isfinite(result[k]) else result[k]) for k in METRICS}}\n\n\n"
                "def correspondence_panel(record, result, limit=60):\n"
                "    \"\"\"image0 | image1 side by side with up to `limit` matches drawn: green within 3 px of the reference, red beyond.\"\"\"\n"
                "    errors = reprojection_errors(result['kpts0'], result['kpts1'], np.asarray(record['homography']))\n"
                "    left, right = record['image0'], record['image1']\n"
                "    canvas = Image.new('RGB', (left.width + right.width + 8, max(left.height, right.height)), (255, 255, 255))\n"
                "    canvas.paste(left, (0, 0))\n"
                "    canvas.paste(right, (left.width + 8, 0))\n"
                "    draw = ImageDraw.Draw(canvas)\n"
                "    step = max(1, len(errors) // limit)\n"
                "    for (x0, y0), (x1, y1), error in list(zip(result['kpts0'], result['kpts1'], errors))[::step][:limit]:\n"
                "        draw.line([(float(x0), float(y0)), (float(x1) + left.width + 8, float(y1))], fill=(40, 170, 75) if error < 3 else (220, 40, 40), width=2)\n"
                "    return canvas, {{'id': record['id'], 'tier': record['tier'], 'matches': int(len(errors)), 'precision_3px': round(float((errors < 3).mean()), 3) if len(errors) else 0.0}}\n\n\n"
                "reset_to_pretrained()\n"
                "t0 = time.perf_counter()\n"
                "baselines = pipe.evaluate_baselines(test_records, progress=show_progress)\n"
                "print({{'baseline_seconds': round(time.perf_counter() - t0, 1), 'per_baseline_seconds': {{name: result['seconds'] for name, result in baselines.items()}}}})\n"
                "for name, result in baselines.items():\n"
                "    print({{name: short(result), 'by_tier': {{tier: short(v) for tier, v in result['by_tier'].items()}}}})\n"
                "t0 = time.perf_counter()\n"
                "frozen_test = pipe.evaluate(test_records, progress=show_progress, stage='frozen model')\n"
                "if frozen_test['adapted']:\n"
                "    raise RuntimeError('Section 6 scored an adapted matcher as the frozen model: re-run Section 5 first (it reloads the pinned base), or restart the session and choose Run all.')\n"
                "print({{'frozen_model_test': short(frozen_test), 'n': frozen_test['n'], 'verdict': frozen_test['verdict'], 'adapted': frozen_test['adapted'], 'seconds': round(time.perf_counter() - t0, 1)}})\n"
                "print({{'by_tier_frozen': {{tier: short(v) for tier, v in frozen_test['by_tier'].items()}}}})\n"
                "print({{'definitions': frozen_test['definitions']}})\n"
                "worst = sorted(frozen_test['per_pair'], key=lambda r: r['precision_3px'])[:3]\n"
                "print({{'weakest_pairs_frozen': [{{k: r[k] for k in ('id', 'tier', 'n_matches', 'precision_3px', 'corner_error_px')}} for r in worst]}})\n"
                "frozen_beats = {{name: frozen_test['precision_3px'] > result['precision_3px'] for name, result in baselines.items()}}\n"
                "print({{'frozen_precision_3px_above': frozen_beats, 'frozen_homography_acc_3px_above_identity': frozen_test['homography_acc_3px'] > baselines['identity']['homography_acc_3px']}})\n"
                "panels = []\n"
                "for tier in ('easy', 'hard'):\n"
                "    record = next((r for r in test_records if r['tier'] == tier), None)\n"
                "    if record is not None:\n"
                "        panels.append(correspondence_panel(record, pipe.match(record['image0'], record['image1'])))\n"
                "figure = Image.new('RGB', (max(p.width for p, _ in panels), sum(p.height for p, _ in panels) + 8 * (len(panels) - 1)), (255, 255, 255))\n"
                "offset = 0\n"
                "for panel, _info in panels:\n"
                "    figure.paste(panel, (0, offset))\n"
                "    offset += panel.height + 8\n"
                "figure.save('outputs/{stem}_correspondences.png')\n"
                "print({{'figure': 'outputs/{stem}_correspondences.png', 'panels (top to bottom)': [info for _panel, info in panels]}})\n"
                "try:\n"
                "    display(figure)\n"
                "except NameError:  # an executor without IPython's display: the figure is saved above\n"
                "    pass"
            ),
        },
        {
            "md": (
                "**What to notice:** the four precision values side by side, the per-tier rows, the weakest pairs, and the two "
                "panels — mostly green on the easy pair, and on the rotated pair fewer lines with red among them.\n\n"
                "<details><summary>Check your reasoning</summary>The rotated tier. In the recorded T4 run the frozen matcher "
                "scored precision at 3 px 0.999 on the easy tier and **0.500** on the hard tier (0.750 overall, 582 matches per "
                "pair, homography accuracy at 3 px 0.708), and all three weakest pairs were rotated pairs with 0.000. The "
                "descriptor nearest neighbour scored 0.981 easy / 0.268 hard (0.624 overall), the patch neighbour 0.652 / 0.040 "
                "(0.346) and the identity guess 0.012 / 0.000 (0.006). So on the easy tier the nine layers add little over the "
                "same descriptors (0.999 against 0.981); their value shows on the rotated tier (0.500 against 0.268) — and that "
                "is still where the matcher comes apart, because neither ALIKED's descriptors nor LightGlue's positional encoding "
                "is rotation-invariant.</details>\n\n"
                "## 7. Bounded fine-tuning of the matcher's last layers\n\n"
                "`pipe.adapt` trains only the last `TRAINABLE_LAYERS` of LightGlue's nine transformer layers (each a "
                "self-attention and a cross-attention block) and the final assignment head (matchability and the final "
                "projection) — 2,567,169 of 11,884,625 parameters by default; ALIKED, the input projection, the positional "
                "encoding, the earlier layers and the per-layer token confidences stay as they are. The ALIKED features of the "
                "training pairs are extracted once and cached — the extractor is frozen, so nothing upstream of the matcher "
                "changes — and each pair runs the matcher to its final log-assignment matrix, scored with the **LightGlue "
                "assignment loss** (the negative log-likelihood of the ground-truth assignment: keypoint pairs under 3 px "
                "reprojection error are positives, keypoints with no partner within 5 px are unmatched, the rest ignored — the "
                "upstream training rule). AdamW at a fixed learning rate, `BATCH_SIZE` pairs accumulated per step (pairs are not "
                "stacked: keypoint counts differ), gradient clipping at 1.0, seeded order, no scheduler. Epoch 0 records the "
                "frozen matcher's validation metrics; every epoch is scored on the 48 validation pairs, and the epoch with the "
                "highest validation **precision at 3 px** is kept (ties broken by homography accuracy).\n\n"
                "The cell first calls `reset_to_pretrained()`, and `adapt` itself refuses a matcher that is already adapted, so "
                "**epoch 0 is always the frozen base** and the exported adapter's manifest describes one training run from it "
                "(`started_from`). The feature caching and each epoch's validation pass print progress lines on a slow runtime.\n\n"
                "**Run-to-run spread.** The fine-tuning result moves by about a hundredth between runtimes (GPU kernels and "
                "floating-point order differ). The same notebook stages gave held-out precision at 3 px **0.765 on the build "
                "workstation's CPU** (2026-09-21, through the package API) and **0.768 on the recorded Kaggle Tesla T4 run** "
                "(2026-09-21, Python 3.12.13, torch 2.14.0+cu130, blob `d5e562ea`); a T4 probe of four longer or wider recipes "
                "landed between 0.771 and 0.777. The two default runs even disagree in direction on one reading: homography "
                "accuracy at 3 px went 0.708 → 0.698 (down) on the CPU and 0.708 → 0.719 (up) on the T4. A change of that size "
                "is a few pairs in 96, so read it as noise, not as an effect.\n\n"
                "**Predict before running:** will the validation precision rise in every epoch? Which tier can the training "
                "still improve, and which is already fitted?"
            ),
            "code": (
                "EPOCHS = 3  # @param {{type:\"integer\"}}\n"
                "LEARNING_RATE = 1e-4  # @param {{type:\"number\"}}\n"
                "BATCH_SIZE = 4  # @param {{type:\"integer\"}}\n"
                "TRAINABLE_LAYERS = 2  # @param {{type:\"integer\"}}\n\n\n"
                "def report(entry):\n"
                "    row = {{'epoch': entry['epoch'], 'train_loss': None if entry['train_loss'] is None else round(entry['train_loss'], 4)}}\n"
                "    if entry.get('val'):\n"
                "        row.update({{'val_' + k: (round(v, 3) if isinstance(v, float) else v) for k, v in entry['val'].items()}})\n"
                "    if 'note' in entry:\n"
                "        row['note'] = entry['note']\n"
                "    print(row)\n\n\n"
                "reset_to_pretrained()\n"
                "t0 = time.perf_counter()\n"
                "adapt_result = pipe.adapt(train_records, val_records, epochs=EPOCHS, lr=LEARNING_RATE, batch_size=BATCH_SIZE, trainable_layers=TRAINABLE_LAYERS, progress=report, stage_progress=show_progress)\n"
                "adapt_seconds = round(time.perf_counter() - t0, 1)\n"
                "print({{'trainable_parameters': adapt_result['n_trainable'], 'total_parameters': adapt_result['n_total'], 'best_epoch': adapt_result['best_epoch'], 'selection': adapt_result['selection'], 'started_from': adapt_result['started_from'], 'ground_truth': adapt_result['ground_truth'], 'feature_seconds': adapt_result['feature_seconds'], 'seed': adapt_result['seed'], 'seconds': adapt_seconds}})"
            ),
        },
        {
            "md": (
                "**What to notice:** epoch 0 is labelled the frozen model, how the training loss and the validation precision "
                "move per epoch, and which epoch is kept.\n\n"
                "<details><summary>Check your reasoning</summary>No. In the recorded T4 run validation precision at 3 px went "
                "0.723 (epoch 0, frozen) → 0.735 → 0.736 → 0.730 while the training loss fell 3.75 → 3.29 → 3.06, so epoch 2 was "
                "kept: the loss kept falling after the validation precision stopped rising — the reason the epoch is chosen on "
                "validation, not on the loss. Validation homography accuracy moved 0.729 → 0.688 → 0.708 → 0.667, differences of "
                "one or two pairs in 48. Only the rotated tier has room to improve: the easy tier is already near 1.0. A run "
                "that keeps epoch 0 is a valid outcome, not a failure.</details>\n\n"
                "## 8. Held-out evaluation\n\n"
                "The test pairs were never used for training or epoch selection, and no photograph appears in two splits. The "
                "adapted matcher is scored exactly as the frozen one was in Section 6, the four systems are put side by side on "
                "every reading, and the per-tier breakdown is repeated. Read it in this order: **precision at 3 px** first (the "
                "metric the epoch was selected on), then the inlier count and the homography accuracy, then the tiers. The cell "
                "records whether the adapted matcher is above, level with or below the frozen one at the printed precision and "
                "prints a one-line reading; nothing is asserted, because a bounded adaptation of a fitted matcher may land flat or "
                "below — the epoch was chosen on 48 validation pairs, not on these 96 — and export and reload in Section 9 run "
                "either way. Each pass adds a row to `run_history`, so a re-run from Section 7 with a changed field can be compared "
                "with the default. Ninety-six pairs from one seeded split give **no dispersion estimate**; the deltas are "
                "sample-sanity evidence that the adaptation contract works, not a benchmark, and a result on rotated bird "
                "photographs says nothing about your scenes until you measure them.\n\n"
                "**Predict before running:** will the overall precision at 3 px rise by more than 0.05? Which tier will carry the "
                "change?"
            ),
            "code": (
                "adapted_test = pipe.evaluate(test_records, progress=show_progress, stage='adapted model')\n"
                "adapted_val = pipe.evaluate(val_records, progress=show_progress, stage='adapted model, validation')\n"
                "comparison = {{metric: {{'identity': round(baselines['identity'][metric], 3), 'patch_neighbour': round(baselines['patch_neighbour'][metric], 3), 'descriptor_nn': round(baselines['descriptor_nn'][metric], 3), 'frozen': round(frozen_test[metric], 3), 'adapted': round(adapted_test[metric], 3)}} for metric in METRICS if np.isfinite(frozen_test[metric]) and np.isfinite(adapted_test[metric])}}\n"
                "comparison['delta_vs_frozen'] = {{metric: round(adapted_test[metric] - frozen_test[metric], 3) for metric in METRICS if np.isfinite(frozen_test[metric]) and np.isfinite(adapted_test[metric])}}\n"
                "comparison['by_tier'] = {{tier: {{'descriptor_nn': short(baselines['descriptor_nn']['by_tier'][tier]), 'frozen': short(frozen_test['by_tier'][tier]), 'adapted': short(adapted_test['by_tier'][tier])}} for tier in adapted_test['by_tier']}}\n"
                "for key, row in comparison.items():\n"
                "    print({{key: row}})\n\n\n"
                "def direction(delta):\n"
                "    return 'up' if delta > 0 else ('level' if delta == 0 else 'down')\n\n\n"
                "delta = comparison['delta_vs_frozen']\n"
                "tier_deltas = {{tier: round(adapted_test['by_tier'][tier]['precision_3px'] - frozen_test['by_tier'][tier]['precision_3px'], 3) for tier in adapted_test['by_tier'] if tier in frozen_test['by_tier']}}\n"
                "outcomes = {{\n"
                "    'adapted_beats_frozen': delta['precision_3px'] > 0,\n"
                "    'precision_3px': direction(delta['precision_3px']),\n"
                "    'homography_acc_3px': direction(delta.get('homography_acc_3px', 0.0)),\n"
                "    'precision_3px_by_tier': {{tier: direction(d) for tier, d in tier_deltas.items()}},\n"
                "    'frozen_beats_baselines': frozen_beats,\n"
                "    'best_epoch': adapt_result['best_epoch'],\n"
                "}}\n"
                "reading = (\n"
                "    f\"precision at 3 px {{comparison['precision_3px']['frozen']:.3f}} -> {{comparison['precision_3px']['adapted']:.3f}} ({{delta['precision_3px']:+.3f}}, {{outcomes['precision_3px']}}); \"\n"
                "    f\"homography accuracy at 3 px {{delta.get('homography_acc_3px', 0.0):+.3f}} ({{outcomes['homography_acc_3px']}}); \"\n"
                "    + '; '.join(f'{{tier}} tier {{d:+.3f}}' for tier, d in tier_deltas.items())\n"
                "    + (f\". The selector kept epoch {{adapt_result['best_epoch']}}.\" if adapt_result['best_epoch'] else '. The selector kept epoch 0 (the frozen matcher): under these settings training did not beat it on validation.')\n"
                "    + ('' if outcomes['adapted_beats_frozen'] else ' The adapted matcher is not above the frozen one on these pairs; that is a result to record, and the export and reload below still run.')\n"
                ")\n"
                "print('Reading: ' + reading)\n"
                "run_history = globals().get('run_history', [])\n"
                "run_history.append({{'run': len(run_history) + 1, 'data_source': data_source, 'trainable_layers': adapt_result['trainable_layers'], 'epochs': adapt_result['epochs'], 'lr': adapt_result['lr'], 'best_epoch': adapt_result['best_epoch'], 'val_epoch0_precision_3px': round(adapt_result['history'][0]['val']['precision_3px'], 3) if adapt_result['history'][0]['val'] else None, 'test_precision_3px': comparison['precision_3px']['adapted'], 'delta_vs_frozen': delta['precision_3px']}})\n"
                "for row in run_history:\n"
                "    print({{'run_history': row}})\n"
                "evaluation_report_payload = {{\n"
                "    'model': {{'id': MODEL_ID, 'revision': MODEL_REVISION, 'key': DEFAULT_MODEL_KEY}},\n"
                "    'data_source': data_source,\n"
                "    'byod': byod,\n"
                "    'dataset_digests': {{name: manifest['digest'] for name, manifest in dataset_manifests.items()}},\n"
                "    'splits': disjoint,\n"
                "    'tiers': TIER_PARAMS,\n"
                "    'baselines': {{name: {{k: v for k, v in result.items() if k != 'per_pair'}} for name, result in baselines.items()}},\n"
                "    'frozen_test': {{k: v for k, v in frozen_test.items() if k != 'per_pair'}},\n"
                "    'frozen_test_per_pair': frozen_test['per_pair'],\n"
                "    'validation_metrics': {{k: v for k, v in adapted_val.items() if k != 'per_pair'}},\n"
                "    'test_metrics': {{k: v for k, v in adapted_test.items() if k != 'per_pair'}},\n"
                "    'test_metrics_per_pair': adapted_test['per_pair'],\n"
                "    'comparison': comparison,\n"
                "    'outcomes': outcomes,\n"
                "    'reading': reading,\n"
                "    'run_history': run_history,\n"
                "    'adaptation': {{k: v for k, v in adapt_result.items() if k not in ('history', 'trainable_names')}},\n"
                "    'history': adapt_result['history'],\n"
                "    'adaptation_seconds': adapt_seconds,\n"
                "}}\n"
                "with open('outputs/{stem}_evaluation_report.json', 'w', encoding='utf-8') as f:\n"
                "    json.dump(evaluation_report_payload, f, indent=2, ensure_ascii=False)\n"
                "print({{'report': 'outputs/{stem}_evaluation_report.json'}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the delta row, the per-tier rows, the printed reading and the run history.\n\n"
                "<details><summary>Check your reasoning</summary>No, and the rotated tier. In the recorded T4 run precision at 3 "
                "px rose 0.750 → 0.768 (+0.018): the easy tier stayed flat (0.999 → 0.998) and the rotated tier carried the "
                "change (0.500 → 0.538). Homography accuracy at 3 px went 0.708 → 0.719 and matches per pair 582 → 578. A gain of "
                "+0.018 is under two pairs' worth of matches in 96 and inside the run-to-run spread of Section 7, so the honest "
                "reading is \"a small gain on the rotated tier, measured once\"; on the build workstation's CPU the same stages "
                "gave 0.765, and there homography accuracy moved *down* (0.708 → 0.698).</details>\n\n"
                "## 9. Re-match the drawn pair, export the adapter and reload it\n\n"
                "The drawn pair from Section 5 is matched again by the adapted model — a drawing, a different image family from "
                "the photographs it was tuned on, so this is a small look at what the adaptation did *outside* its corpus (a "
                "changed count or precision here is a finding to record, not a failure) — and reported with the per-pair "
                "`evaluation_report` (`sample-sanity`). Both match sets are written as JSON.\n\n"
                "`pipe.save_artifact` writes the trained tensors — the matcher's last layers and the assignment head, about "
                "10.3 MB — as `adapter.safetensors`, with a `manifest.json` recording the artifact format, the base "
                "model id and revision, the digests of the base `aliked_lightglue.safetensors` and `aliked-n16.safetensors`, "
                "the tensor names, the file size and SHA-256, the training configuration, `started_from` and the epoch history "
                "(OUT8). `LightGluePipeline.from_artifact` re-verifies the base snapshot, checks the artifact manifest, its "
                "digest and its exact tensor set **before** deserialising, refuses any tensor outside the matcher, and overlays "
                "the tensors onto a freshly loaded base — a new object from files, not the in-memory model (VER2). The cell "
                "compares the matches of the two on four test pairs (VER4) and stops with an explanation if they differ.\n\n"
                "**Predict before running:** after tuning on rotated bird photographs, will the adapted matcher still match the "
                "drawing as well as the frozen one did? Will the reloaded adapter give exactly the same matches?"
            ),
            "code": (
                "import shutil\n\n"
                "adapted_scene_match = pipe.match(scene_path, scene1_path)\n"
                "adapted_scene_errors = reprojection_errors(adapted_scene_match['kpts0'], adapted_scene_match['kpts1'], SHAPES_H)\n"
                "adapted_scene = evaluation_report(adapted_scene_match, {{'homography': SHAPES_H, 'size': adapted_scene_match['size0']}}, sample_kind='synthetic')\n"
                "scene_rows['adapted'] = {{'n_matches': int(len(adapted_scene_match['kpts0'])), 'precision_3px': float((adapted_scene_errors < 3).mean()) if len(adapted_scene_errors) else 0.0, 'median_error_px': float(np.median(adapted_scene_errors)) if len(adapted_scene_errors) else None}}\n"
                "print({{'scene': scene_rows, 'scene_after_adaptation': {{m['id']: round(m['value'], 3) for m in adapted_scene['metrics']}}, 'verdict': adapted_scene['verdict']}})\n"
                "with open('outputs/{stem}_shapes.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump({{'reference_homography': SHAPES_H.tolist(), 'frozen': {{'kpts0': scene_match['kpts0'].tolist(), 'kpts1': scene_match['kpts1'].tolist(), 'confidence': scene_match['confidence'].tolist()}}, 'adapted': {{'kpts0': adapted_scene_match['kpts0'].tolist(), 'kpts1': adapted_scene_match['kpts1'].tolist(), 'confidence': adapted_scene_match['confidence'].tolist()}}, 'rows': scene_rows}}, handle, indent=2)\n"
                "artifact_dir = Path('outputs/{stem}_adapter')\n"
                "shutil.rmtree(artifact_dir, ignore_errors=True)\n"
                "pipe.save_artifact(artifact_dir, metadata={{'tutorial': '{stem}', 'data_source': data_source}})\n"
                "artifact_manifest = json.loads((artifact_dir / 'manifest.json').read_text(encoding='utf-8'))\n"
                "print({{'artifact': str(artifact_dir), 'format': artifact_manifest['format'], 'tensors': len(artifact_manifest['tensors']), 'bytes': artifact_manifest['files'][0]['bytes'], 'sha256': artifact_manifest['files'][0]['sha256'][:16] + '...', 'best_epoch': artifact_manifest['adapter']['best_epoch'], 'started_from': artifact_manifest['adapter']['started_from'], 'trainable_layers': artifact_manifest['adapter']['trainable_layers']}})\n"
                "reloaded = LightGluePipeline.from_artifact(artifact_dir, weights_dir=WEIGHTS_DIR, device=pipe.device)\n"
                "identical = 0\n"
                "for record in test_records[:4]:\n"
                "    before, after = pipe.match(record['image0'], record['image1']), reloaded.match(record['image0'], record['image1'])\n"
                "    identical += int(len(before['kpts0']) == len(after['kpts0']) and np.allclose(before['kpts1'], after['kpts1'], atol=1e-4))\n"
                "parity = {{'identical_pairs': identical, 'of': len(test_records[:4])}}\n"
                "print({{'reload_parity': parity, 'reloaded_best_epoch': reloaded.adapter['best_epoch']}})\n"
                "if parity['identical_pairs'] != parity['of']:\n"
                "    raise RuntimeError(f'Reload parity failed: {{parity}}. The saved adapter does not reproduce the evaluated matcher; re-run from Section 7 (it reloads the pinned base first) or restart the session and choose Run all.')\n\n"
                "write_provenance('outputs/provenance.json', pipeline=pipe)\n"
                "result_payload = {{\n"
                "    'notebook_source': NOTEBOOK_SOURCE,\n"
                "    'repository_revision': NOTEBOOK_SOURCE['repository_revision'],\n"
                "    'model_id': MODEL_ID,\n"
                "    'model_revision': MODEL_REVISION,\n"
                "    'model_license': MODEL_LICENSE,\n"
                "    'snapshot': {{'path': str(WEIGHTS_DIR), 'files': snapshot['files'], 'fetched_this_run': fetched, 'weight_file': MODEL_FILENAME, 'weight_format': 'safetensors, converted once from the audited source pickle, digest-verified', 'weight_sha256': MODEL_SHA256, 'extractor_file': EXTRACTOR_FILENAME, 'extractor_sha256': EXTRACTOR_SHA256, 'vendored_code': {{'lightglue': {{'repository': UPSTREAM_REPOSITORY, 'commit': UPSTREAM_COMMIT}}, 'aliked': {{'repository': ALIKED_REPOSITORY, 'commit': EXTRACTOR_COMMIT}}}}}},\n"
                "    'data_source': data_source,\n"
                "    'byod': byod,\n"
                "    'corpus': None if USE_BYOD else {{'name': CORPUS_NAME, 'release': CORPUS_RELEASE, 'license': CORPUS_LICENSE, 'base_url': CORPUS_BASE_URL, 'bytes': CORPUS_BYTES, 'pinned_photographs': len(SAMPLE_RECORDS), 'tiers': TIER_PARAMS}},\n"
                "    'inference_contract': {{'input_manifest': input_manifest, 'sanity_checks': checks, 'scene': {{'sha256': scene_digest, 'reference_homography': SHAPES_H.tolist()}}, 'frozen_report': frozen_scene, 'adapted_report': adapted_scene, 'scene_rows': scene_rows}},\n"
                "    'comparison': comparison,\n"
                "    'outcomes': outcomes,\n"
                "    'reading': reading,\n"
                "    'artifact': {{'dir': str(artifact_dir), 'sha256': artifact_manifest['files'][0]['sha256'], 'bytes': artifact_manifest['files'][0]['bytes'], 'tensors': len(artifact_manifest['tensors']), 'started_from': artifact_manifest['adapter']['started_from']}},\n"
                "    'reload_parity': parity,\n"
                "    'runtime': {{'python': platform.python_version(), 'torch': torch.__version__, 'numpy': numpy.__version__, 'device': str(pipe.device), 'dtype': 'float32', 'checkpoint_source': pipe.checkpoint_source}},\n"
                "}}\n"
                "with open('outputs/{stem}_result.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(result_payload, handle, indent=2, ensure_ascii=False)\n"
                "print(sorted(os.listdir('outputs')))"
            ),
        },
        {
            "md": (
                "**What to notice:** what changed in the drawing's matches, the artifact's tensor count, size and "
                "`started_from`, and the reload-parity line.\n\n"
                "<details><summary>Check your reasoning</summary>Yes, and yes. In the recorded T4 run the adapted matcher returned "
                "the same 32 matches on the drawing, all within 3 px (median error 0.34 px, as before): tuning the last two "
                "layers on rotated photographs did not disturb this easy, unrotated drawing — one image of evidence, not a "
                "measurement. The artifact held 48 tensors, 10,273,700 bytes, and reload parity was 4/4: the exported adapter is "
                "the matcher that was evaluated. Parity holds because training started from the pinned base, so the adapter "
                "carries every tensor that differs from it.</details>\n\n"
                "## 10. Your turn — change one thing: train four layers instead of two\n\n"
                "Optional and **off by default**; **Predict → Change one thing → Run → Observe → Explain**. The cell trains a "
                "*fresh copy of the pinned base* (`experiment_pipe`), so `pipe`, the Section 8 report and the Section 9 adapter "
                "stay exactly as they are; its results go to `outputs/{stem}_experiment.json` and its adapter to "
                "`outputs/{stem}_experiment_adapter/`. It retrains and re-scores the test pairs, so it takes about as long as "
                "Sections 7 and 8 did (130 s of training on the T4 record; about 35 minutes on a workstation CPU).\n\n"
                "1. **Predict:** with `EXPERIMENT_TRAINABLE_LAYERS = 4` (4 of the 9 layers plus the head, about twice the trained "
                "parameters), will the held-out precision at 3 px land above the default run's, and by more than the run-to-run "
                "spread? How will the adapter's size change? Write your guesses beside the default row of `run_history`.\n"
                "2. **Change:** set `RUN_EXPERIMENT = True`. Change nothing else (the other fields repeat the defaults).\n"
                "3. **Run:** run this cell only.\n"
                "4. **Observe:** epoch 0's validation precision must equal the default run's epoch 0 — the sign that the "
                "experiment started from the base, not from the adapted matcher (`starts_from_base` is printed). Then read the "
                "kept epoch, the held-out precision overall and on the rotated tier, and the adapter size.\n"
                "5. **Explain:** in one or two sentences, what did training more layers change, and is the difference from the "
                "default run larger than the run-to-run spread and what 96 test pairs can resolve?\n\n"
                "**Predict before running:** as in step 1."
            ),
            "code": (
                "RUN_EXPERIMENT = False  # @param {{type:\"boolean\"}}\n"
                "EXPERIMENT_TRAINABLE_LAYERS = 4  # @param {{type:\"integer\"}}\n"
                "EXPERIMENT_EPOCHS = 3  # @param {{type:\"integer\"}}\n"
                "EXPERIMENT_LEARNING_RATE = 1e-4  # @param {{type:\"number\"}}\n\n"
                "if not RUN_EXPERIMENT:\n"
                "    print({{'experiment': 'not run (RUN_EXPERIMENT = False)', 'to run it': 'set RUN_EXPERIMENT = True and run this cell; the default results above are not changed'}})\n"
                "else:\n"
                "    experiment_pipe = LightGluePipeline.from_pretrained(weights_dir=WEIGHTS_DIR)  # a fresh pinned base; `pipe` is untouched\n"
                "    t0 = time.perf_counter()\n"
                "    experiment_result = experiment_pipe.adapt(train_records, val_records, epochs=EXPERIMENT_EPOCHS, lr=EXPERIMENT_LEARNING_RATE, batch_size=BATCH_SIZE, trainable_layers=EXPERIMENT_TRAINABLE_LAYERS, progress=report, stage_progress=show_progress)\n"
                "    experiment_test = experiment_pipe.evaluate(test_records, progress=show_progress, stage='experiment, test')\n"
                "    experiment_dir = Path('outputs/{stem}_experiment_adapter')\n"
                "    shutil.rmtree(experiment_dir, ignore_errors=True)\n"
                "    experiment_pipe.save_artifact(experiment_dir, metadata={{'tutorial': '{stem}', 'data_source': data_source, 'experiment': 'Section 10'}})\n"
                "    experiment_manifest = json.loads((experiment_dir / 'manifest.json').read_text(encoding='utf-8'))\n"
                "    default_epoch0 = adapt_result['history'][0]['val']\n"
                "    experiment_epoch0 = experiment_result['history'][0]['val']\n"
                "    experiment = {{\n"
                "        'changed': {{'trainable_layers': [adapt_result['trainable_layers'], EXPERIMENT_TRAINABLE_LAYERS], 'epochs': [adapt_result['epochs'], EXPERIMENT_EPOCHS], 'lr': [adapt_result['lr'], EXPERIMENT_LEARNING_RATE]}},\n"
                "        'starts_from_base': experiment_epoch0 == default_epoch0,\n"
                "        'epoch0_val_precision_3px': round(experiment_epoch0['precision_3px'], 3) if experiment_epoch0 else None,\n"
                "        'trainable_parameters': experiment_result['n_trainable'],\n"
                "        'best_epoch': experiment_result['best_epoch'],\n"
                "        'test_precision_3px': {{'frozen': round(frozen_test['precision_3px'], 3), 'default_adapted': round(adapted_test['precision_3px'], 3), 'experiment': round(experiment_test['precision_3px'], 3)}},\n"
                "        'test_precision_3px_by_tier': {{tier: {{'frozen': round(frozen_test['by_tier'][tier]['precision_3px'], 3), 'default_adapted': round(adapted_test['by_tier'][tier]['precision_3px'], 3), 'experiment': round(v['precision_3px'], 3)}} for tier, v in experiment_test['by_tier'].items()}},\n"
                "        'adapter_bytes': {{'default': artifact_manifest['files'][0]['bytes'], 'experiment': experiment_manifest['files'][0]['bytes']}},\n"
                "        'seconds': round(time.perf_counter() - t0, 1),\n"
                "    }}\n"
                "    with open('outputs/{stem}_experiment.json', 'w', encoding='utf-8') as handle:\n"
                "        json.dump({{**experiment, 'history': experiment_result['history']}}, handle, indent=2, ensure_ascii=False)\n"
                "    for key, value in experiment.items():\n"
                "        print({{key: value}})"
            ),
        },
    ],
    "closing": (
        "**What to notice:** `starts_from_base` (it must be `True`), the kept epoch, the overall and rotated-tier precision "
        "beside the default run and the frozen matcher, and the adapter size.\n\n"
        "<details><summary>Check your reasoning</summary>A little higher, but not by much more than the spread. This "
        "notebook's recorded runs never executed the experiment cell, so there is no recorded answer for your exact numbers; "
        "the closest evidence is the build record's Kaggle T4 probe of four longer or wider recipes through the package API "
        "(up to lr 3e-4 × 8 epochs on the last four layers), which all landed between 0.771 and 0.777 against the default's "
        "0.765–0.768 — a plateau: the last matcher layers learn a few more rotated correspondences from frozen, "
        "rotation-variant descriptors and no more. Four layers roughly double the trained parameters (about 5.1 M) and the "
        "adapter's size. A difference of 0.01 is about one pair in 96: if your experiment moves by that much, it is "
        "consistent with noise.</details>\n\n"
        "## Interpretation and limits\n\n"
        "The frozen matcher is a strong correspondence engine on the easy tier — in the recorded Kaggle Tesla T4 run, precision "
        "at 3 px of 0.999 with 838 matches per easy pair — and comes apart on the rotated tier (0.500), where its own "
        "descriptors matched by nearest neighbour fall further (0.268). In that run a bounded fine-tuning of the matcher's last "
        "two layers and assignment head on 216 pairs moved precision at 3 px from 0.750 to 0.768 (+0.018) with epoch 2 kept, "
        "homography accuracy at 3 px 0.708 → 0.719, and matches per pair 582 → 578; on the rotated tier precision went 0.500 → "
        "0.538 (homography accuracy 0.417 → 0.438), on the easy tier 0.999 → 0.998. The build workstation's CPU run of the same "
        "stages kept epoch 2 too but gave 0.765, with homography accuracy moving the other way (0.708 → 0.698 overall, 0.417 → "
        "0.396 on the rotated tier): your own run's numbers, printed above, are the ones to interpret. A Tesla T4 probe of four "
        "longer or wider arms (up to lr 3e-4 × 8 epochs on the last four layers) landed every one between 0.771 and 0.777 — a "
        "plateau. That is the claim: the adaptation contract works end to end on a labelled pair set with exact references, "
        "and the numbers it produces are read on precision, inlier count and homography accuracy, per tier, against three "
        "baselines and the frozen model rather than in isolation.\n\n"
        "The test split is 96 pairs from one seeded draw of one sample, the validation split that picks the epoch is 48, the "
        "warps are synthetic (a photograph and its own perspective-warped, re-lit copy — no viewpoint change of a real scene, no "
        "occlusion), the metrics are reference-based scores (own numpy implementations; none a human judgement), and the "
        "recorded epoch history shows the estimate's fragility: validation precision at 3 px moved 0.723 → 0.735 → 0.736 → "
        "0.730 over epochs 0–3 and homography accuracy 0.729 → 0.688 → 0.708 → 0.667, differences of a few pairs in 48. So a "
        "gain here says the contract works; it does not say the adapted matcher is better on your images, that its confidences "
        "are calibrated, or that a match with a high confidence is right — it still returns matches for every pair, and it can "
        "be wrong confidently. Fine-tuning on a narrow set can also erode the model elsewhere; the drawn pair re-matched in "
        "Section 9 is one image of evidence about that, not a measurement.\n\n"
        "Three things to carry to real data. **Baselines first:** the identity guess, the patch neighbour, the descriptor "
        "neighbour and the frozen matcher's score on *your* pairs are the numbers to read before any adapted one, per tier and "
        "on the homography reading. **Leakage:** keep every photograph in one split (the contract de-duplicates by decoded "
        "pixels) and split by scene, session or photographer when your images come from few sources — the sample's observer "
        "overlap is printed for exactly that reason. **References:** a synthetic warp gives an exact `H`; real pairs need "
        "depth, pose or a fitted homography before they can be scored, and a fitted homography is itself an estimate.\n\n"
        "Successful execution proves that the recorded repository revision's package, carried in this standalone notebook, can "
        "acquire, digest-verify, audit and convert the pinned checkpoint pickles into its vendored network, fetch and "
        "digest-verify a real photograph set and build exact-reference pairs from it, validate the demonstrated dataset contract "
        "with a photograph-disjoint split, execute the inference contract and a bounded fine-tuning from the pinned base, "
        "evaluate against three baselines and the frozen model on an image-disjoint split, and emit the shown machine-readable "
        "artifacts — without the repository being reachable. It does **not** establish benchmark superiority, matching accuracy "
        "on real viewpoint changes, rotation invariance in general, other extractors or other cameras, calibration, or "
        "production fitness.\n\n"
        "**Optional experiments (they do not affect the default path):** Section 10 trains four layers on a fresh copy of the "
        "base. To try another setting through the main path instead, change one Section 7 field (`EPOCHS`, `LEARNING_RATE` "
        "— for example `1e-5` for a smaller, steadier change — or `TRAINABLE_LAYERS`), select Section 7 and choose **Run "
        "after**: Section 7 reloads the base before training, Section 8 compares against the same frozen score and adds a row "
        "to `run_history`, and Section 9 exports the new adapter. To try another split, change `SPLIT_SEED` in Section 4 and "
        "choose **Run after** there. To bring your own photographs, use BYOD (Section 4) and read the three baselines before "
        "the adapted number.\n\n"
        "## Troubleshooting\n\n"
        "- **Section 1 stops with \"needs a Linux x86_64 runtime\".** The locked environment is built from manylinux wheels. "
        "Use Google Colab, Kaggle or a Linux Jupyter server; Windows and macOS kernels are not supported.\n"
        "- **Section 1 fails while downloading** (`uv` wheel, Python build or packages). The runtime needs PyPI and the "
        "python-build-standalone download; run the cell again once the network is back. A \"size/SHA-256\" or \"does not "
        "match its digest\" error means a file was altered: do not edit the cell, regenerate the notebook from the "
        "repository.\n"
        "- **A stage seems stuck.** On CPU the baselines take about 20 minutes and the fine-tuning about 35 (more on a 2-vCPU "
        "runtime); watch for the `progress` lines, printed at least every 30 seconds. A GPU runtime (**Runtime → Change "
        "runtime type**) is faster, but the patch-neighbour baseline runs on the CPU on every runtime.\n"
        "- **\"The isolated environment's Python process exited\" or an out-of-memory error.** The runtime ran out of memory. "
        "Restart the session and choose **Run all**; in Section 7, `BATCH_SIZE = 2` needs less memory.\n"
        "- **A `sha256`/`size` `ValueError` or `FileNotFoundError` in Section 3.** A staged checkpoint is incomplete or altered "
        "— delete it from `weights/lightglue-aliked/` and run Section 3 again. A photograph digest mismatch in Section 4 is "
        "the same for the cache under `weights/inat-birds/`; a download error there means the iNaturalist bucket was "
        "unreachable — run Section 4 again.\n"
        "- **BYOD is refused in Section 4.** The message names what to fix: too few photographs for the split (at least 12 "
        "distinct photographs; it names the split that would be short), no JPEG / PNG files in the zip, a file that is not "
        "a zip or folder, or a path that does not exist. Fix it and run Section 4 with **Run after** again. An empty or "
        "cancelled upload, or a runtime without the Colab upload dialog, asks you to choose a file or set `BYOD_PATH`. Small "
        "photographs are not refused but reported as upscaled.\n"
        "- **Section 8 reads \"not above the frozen one\" or \"The selector kept epoch 0\".** Not an error: under these "
        "settings the adaptation did not beat the frozen matcher. Read the epoch history in Section 7; the export and reload "
        "in Section 9 still run.\n"
        "- **\"this pipeline already holds an adapted matcher\" from `adapt`.** Training starts from the pinned base only. "
        "Re-run Section 7 (it calls `reset_to_pretrained()` first) rather than calling `pipe.adapt` again by hand.\n"
        "- **Reload parity fails in Section 9.** The saved adapter does not reproduce the evaluated matcher. Re-run from "
        "Section 7, or restart the session and choose **Run all**.\n"
        "- **Numbers differ from the worked answers.** Frozen numbers move only in the third decimal between runtimes; the "
        "fine-tuning result by about a hundredth (Section 7, **Run-to-run spread**). Larger differences on the default "
        "settings mean a form field was changed.\n"
        "- **You re-ran the routing cell in Section 1.** It starts a new isolated process and discards every variable "
        "created so far; choose **Run all** again.\n\n"
        "## Glossary\n\n"
        "- **Keypoint / descriptor:** a distinctive image location (a corner, a blob) and the 128-number vector ALIKED computes "
        "to describe its neighbourhood.\n"
        "- **Sparse matching:** pairing keypoints of one image with keypoints of the other, rather than every pixel.\n"
        "- **Homography `H`:** the 3 × 3 matrix that maps image0 coordinates to image1 coordinates for a planar scene or a "
        "warped copy; here it is exact by construction.\n"
        "- **Reprojection error:** the distance in pixels between where a match puts a point in image1 and where `H` says it "
        "is.\n"
        "- **Precision at 3 px:** the share of returned matches with reprojection error under 3 px, averaged over pairs; an "
        "**inlier** is one such match.\n"
        "- **Homography accuracy:** the share of pairs whose homography fitted from the matches (RANSAC-DLT) moves the image "
        "corners by less than 3 (or 5) px against the reference.\n"
        "- **Confidence:** LightGlue's assignment score for a match — a ranking signal above a threshold, not a probability; "
        "the matcher never abstains.\n"
        "- **Identity / patch / descriptor baselines:** no-model and no-matcher references: same coordinates, best raw-pixel "
        "patch nearby, and ALIKED descriptors paired by mutual nearest neighbour.\n"
        "- **Easy / hard tier:** two families of synthetic warps; the hard tier rotates up to ±150°.\n"
        "- **Assignment loss:** the training objective — the negative log-likelihood of the correct match (or no-match) for "
        "every keypoint, from the reference `H`.\n"
        "- **Epoch / validation selection:** one pass over the training pairs; the epoch kept is the one with the highest "
        "validation precision at 3 px (epoch 0 = the frozen matcher).\n"
        "- **Training / validation / test split:** pairs used to train, to choose the epoch, and to report the final result "
        "once; split by photograph, so no photograph is in two splits.\n"
        "- **safetensors / adapter / reload parity:** a tensor file format that cannot run code when loaded; the saved trained "
        "tensors; and the check that a pipeline rebuilt from them and the pinned base gives the same matches.\n"
        "- **Pickle audit:** reading a checkpoint's pickle stream as data and refusing it unless it names only the four "
        "allowed constructors, before the weights-only unpickler opens it once.\n\n"
        "## Conclusion (your notes)\n\n"
        "Optional personal notes, not a required submission. Complete each sentence from your own run:\n\n"
        "- On the test pairs the identity guess scored precision at 3 px ___, the patch neighbour ___, the descriptor "
        "neighbour ___, the frozen matcher ___ and the adapted matcher ___ (kept epoch ___).\n"
        "- On the rotated tier the frozen matcher scored ___ and the adapted one ___; on the easy tier ___ and ___, so the "
        "change came from ___.\n"
        "- Homography accuracy moved from ___ to ___; compared with the run-to-run spread that is ___.\n"
        "- On the drawn pair, the adaptation changed ___.\n"
        "- Training four layers (Section 10) changed ___; the difference from the default is / is not larger than the "
        "run-to-run spread, because ___.\n"
        "- Before trusting this adaptation on my own images I would measure ___ on ___, split by ___, with the baselines "
        "first.\n\n"
        "## References\n\n"
        "- Repository README: https://github.com/kurtvalcorza/lightglue-matching-pipeline/blob/main/README.md\n"
        "- Repository model card: https://github.com/kurtvalcorza/lightglue-matching-pipeline/blob/main/MODEL_CARD.md\n"
        "- Sample dataset card (synthetic scene): https://github.com/kurtvalcorza/lightglue-matching-pipeline/blob/main/examples/sample-data/DATASET_CARD.md\n"
        "- Upstream matcher weights and code: https://github.com/cvg/LightGlue (release `v0.1_arxiv`; the matcher and the ALIKED port vendored as `modeling.py` at the commit recorded in `docs/WEIGHTS.md`)\n"
        "- Upstream extractor weights: https://github.com/Shiaoming/ALIKED (`models/aliked-n16.pth` at the pinned commit)\n"
        "- LightGlue: Local Feature Matching at Light Speed (Lindenberger, Sarlin and Pollefeys, ICCV 2023): https://arxiv.org/abs/2306.13643\n"
        "- ALIKED: A Lighter Keypoint and Descriptor Extraction Network via Deformable Transformation (Zhao et al., IEEE TIM 2023): https://arxiv.org/abs/2304.03608\n"
        "- iNaturalist open data (CC0 photographs, each observer's own licence): https://www.inaturalist.org/pages/developers — bucket https://inaturalist-open-data.s3.amazonaws.com/\n"
        "- DIMER Notebook Specification 2.2 and Model Card Specification 1.1 (fleet specs in the ml-worker repository)"
    ),
}
